-- CREACIAON DE BASE DE DATOS PARA SISTEMA UNIVERSITARIO
CREATE DATABASE SISTEMA_U;
USE SISTEMA_U;

--CREACION DE TABLA PROFESOR
CREATE TABLE Profesor (
    Registro INT PRIMARY KEY , 
    NombreProfesor VARCHAR(200) NOT NULL
    );

-- CREACION DE TABLA CURSO
CREATE TABLE Curso(
    Codigo INT PRIMARY KEY,
    NombreCurso VARCHAR(200) NOT NULL
);

-- CREACION DE TABLA ESTUDIANTE
-- 202030962
CREATE TABLE Estudiante(
    Carnet INT PRIMARY KEY,
    Nombre VARCHAR(200) NOT NULL
);

-- CREACION DE TABLA ASIGNACION
CREATE TABLE Asignacion(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Carnet INT,
    Codigo INT
);

ALTER TABLE Curso ADD Registro INT;

ALTER TABLE Curso 
ADD CONSTRAINT  FK_PROFESOR
FOREIGN KEY(Registro) REFERENCES Profesor(Registro);

ALTER TABLE Asignacion 
ADD CONSTRAINT  FK_ESTUDIANTE
FOREIGN KEY(Carnet) REFERENCES Estudiante(Carnet);

ALTER TABLE Asignacion 
ADD CONSTRAINT  FK_CURSO
FOREIGN KEY(Codigo) REFERENCES Curso(Codigo);

INSERT INTO Profesor VALUES (2020, "Daniel Gonzalez");

INSERT INTO Profesor (NombreProfesor, Registro) VALUES ("Juan Miranda", 2000);
INSERT INTO Profesor (NombreProfesor, Registro) VALUES ("Mauricio Perez", 1000);

INSERT INTO Curso VALUES (1111, "IPC2", 2020);

